export const INTERNAL_DISPLAY_TOAST = 'INTERNAL_DISPLAY_TOAST'
export const USER_RECORD_START = 'USER_RECORD_START'
export const USER_RECORD_SUCCESS = 'USER_RECORD_SUCCESS'
export const USER_RECORD_ERROR = 'USER_RECORD_ERROR'
