#!/usr/bin/env bash

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

printf "Running linters:\n"
linter=$(task lint)
ret_code=$?

# Run linters and check return code
if [ $ret_code != 0 ]; then
  printf "${RED}Failed; commit was not created${NC}\n"
  pass=false
else
  printf "${GREEN}Successfully completed${NC}\n"
fi

# If there were no failures, it is good to commit
if $pass; then
  exit 0
fi

exit 1
