language: go
go:
  - "1.11.1"
services:
  - postgresql
env:
  global:
    - ENV=testing
    - GO111MODULE=on
before_script:
  - go version; go env
  - psql -c 'create database space_test;' -U postgres
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - bin/linter
after_success:
  - bash <(curl -s https://codecov.io/bash)
