language: go
go:
  - "1.19.12"
services:
  - postgresql
  - redis
env:
  global:
    - GO111MODULE=on
    - SPACE_ENV=testing
    - GIN_MODE=test
    - NODE_ENV=development
install:
  - npm install
before_script:
  - go version; go env
  - psql -c 'create database space_test;' -U postgres
  - mv .config.ci.json .config.local.json
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - scripts/lint-all.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
