coverage:
  round: down
  precision: 2
  status:
    project:
      default:
        target: 45%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 10%
        threshold: null

comment:
  layout: "header, diff, flags, components, tree"
  behavior: default
  require_changes: true
