version: '3.5'

networks:
  projects:
    name: quatrolabs-projects-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24

services:
  space-redis:
    image: 'redis:5.0.0'
    container_name: space-redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: space-redis
    expose:
      - "6379"
    restart: always
    volumes:
      - space-redis-data:/data
    networks:
      - projects

  space-postgres:
    image: 'postgres:9.6.10'
    container_name: space-postgres
    hostname: space-postgres
    expose:
      - "5432"
    restart: always
    volumes:
      - space-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: space
      POSTGRES_PASSWORD: 8GWbz2JF4FMe1Q8X
      POSTGRES_DB: space_production
    networks:
      - projects

  space:
    build:
      context: .
    container_name: space
    image: space
    restart: always
    ports:
      - "8484:9000"
    networks:
      - projects

volumes:
  space-redis-data:
  space-postgres-data:
