version: '3.5'

networks:
  quatrolabs-network:
    driver: bridge
  quatrolabs-space-network:
    driver: bridge

services:
  space-redis:
    image: 'redis:5.0.0'
    container_name: space-redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: space-redis
    expose:
      - "6379"
    restart: always
    volumes:
      - space-redis-data:/data
    networks:
      - quatrolabs-space-network

  space-postgres:
    image: 'postgres:9.6.10'
    container_name: space-postgres
    hostname: space-postgres
    expose:
      - "5432"
    restart: always
    volumes:
      - space-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: space_development
      POSTGRES_HOST_AUTH_METHOD: "trust"
      listen_addresses: "*"
    networks:
      - quatrolabs-space-network

  space:
    build:
      context: .
    container_name: space
    image: space
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - space-web-public:/app/web/public
    networks:
      - quatrolabs-space-network
      - quatrolabs-network

volumes:
  space-redis-data:
  space-postgres-data:
  space-web-public:
