package api

func (s *ApiTestSuite) TestEndpoints() {
	w := s.PerformRequest(s.Router, "GET", "/api/health-check", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/clients/1/credentials", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/clients", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/clients", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "PATCH", "/api/clients/1/profile", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/users/me/requests", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/users/me/requests", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/users/me/workspace", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "PATCH", "/api/users/me/password", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "PATCH", "/api/users/me/admin", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/users/me/emails", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/users/me/emails", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/users/me/settings", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "PATCH", "/api/users/me/settings", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/services", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/services", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/sessions/requests", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/sessions", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "POST", "/api/users", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/users/1/profile", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/users/1/clients", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "DELETE", "/api/users/1/clients/1/revoke", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "GET", "/api/users/1/sessions", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
	w = s.PerformRequest(s.Router, "DELETE", "/api/users/1/sessions/1/revoke", nil, nil, nil)
	s.Require().NotEqual(404, w.Code)
}
