export const INTERNAL_LOADING_CONTEXT_ADD = 'INTERNAL_LOADING_CONTEXT_ADD';
export const INTERNAL_LOADING_CONTEXT_REMOVE = 'INTERNAL_LOADING_CONTEXT_REMOVE';
export const INTERNAL_LOAD_DATA = 'INTERNAL_LOAD_DATA';
export const INTERNAL_ERROR_HANDLING = 'INTERNAL_ERROR_HANDLING';
