[settings]
storage_secret = ""

[mailer]
mail_from = "example@example.com"
mail_key = "AccessKeyId:SecretAccessKey:Region"

[datastore]
host = "localhost"
user = "postgres"
password = ""
database_prefix = "space"
sslmode = "disable"
key_secret = "secret"

[http]
port = 8080
session_secret = "secret"
