[settings]
storage_secret = ""

[datastore]
host = "localhost"
user = "postgres"
password = ""
database_prefix = "space"
sslmode = "disable"
key_secret = "secret"

[http]
port = 8080
session_secret = "secret"
