#!/bin/bash

PROJECT=''

if [ $(git rev-parse --is-bare-repository) = true ]
then
    PROJECT=$(basename "$PWD")
else
    echo "Not running inside a bare repository; skipping..."
    exit
fi

while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        mkdir -p $HOME/.apps
        mkdir -p $HOME/.apps/$PROJECT
        echo "Revision $newrev received. Deploying master branch to production..."
        git --work-tree=$HOME/.apps/$PROJECT --git-dir=$HOME/$PROJECT checkout -f
        cd $HOME/.apps/$PROJECT && bin/deploy $oldrev $newrev
    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
